### PR TITLE
Simplify getting started for newcomers

### PR DESCRIPTION
**Pull request by gabor-boros**
## Description

This PR simplifies the process to get started with the development, removes unnecessary steps, reduces the effort to set up the repository, and fixes smaller config-related bugs. In addition, the CI steps were refactored to include benchmarks, front-end tests, and additional linters.

## Supporting information

Link to other information about the change, such as, GitHub issues or documentation.

* Fixes https://github.com/opcotech/elemo/issues/158
* Resolves https://github.com/opcotech/elemo/issues/139

### Dependencies

N/A

### Screenshots

N/A

## Testing instructions

1. proofread the updated documentation
2. clone the repository (we need a fresh setup)
3. checkout the related branch
4. run `./scripts/setup.sh`
5. run `pnpm --prefix web dlx playwright install --with-deps`
6. run `make test`

## Other information

The original mailhog image is not compatible with arm64 architectures, hence it was replaced with a ["fork"](https://github.com/mailhog/MailHog/issues/454#issuecomment-1836481872).

## Checklist

- [x] I have read and understood the [Developer's Certificate of Origin] and
  added `Signed-off-by: <YOUR NAME>` to the commit trail where `<YOUR NAME>` is
  my name.

### Documentation

- Documentation comments are updated
- Documentation site is updated

### Review

- Reviewed the code based on Go's [code review guide]
- Reviewed the code based on Go's [concurrency review guide]

### Miscellaneous

- Pull request is rebased onto main
- Commit history is clean

[Developer's Certificate of Origin]: https://github.com/opcotech/elemo/blob/main/CONTRIBUTING.md#developers-certificate-of-origin

[code review guide]: https://github.com/golang/go/wiki/CodeReviewComments

[concurrency review guide]: https://github.com/golang/go/wiki/CodeReviewConcurrency

### CODE REVIEW

**Review by nizarmah — COMMENTED** [review]
Thanks for the changes! I'm still running into the same issue unfortunately.

The docker compose env name and the bug report scripts are a nice addition. 

### Setup script fails to initialize relational database

**Logs**

```
> ./scripts/setup.sh
2024/04/23 21:29:57 License generated: /Users/elmo/elemo/configs/development/license.gen.key
[+] Running 6/6
 ✔ neo4j 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                       63.5s 
   ✔ ebc3dc5a2d72 Pull complete                                                                                                        13.7s 
   ✔ 9701f65253cb Pull complete                                                                                                        57.0s 
   ✔ 35efb11ab5fe Pull complete                                                                                                         1.4s 
   ✔ 701ed5e8b2fb Pull complete                                                                                                         2.7s 
   ✔ 56ca08505b7f Pull complete                                                                                                        45.3s 
[+] Running 5/5
 ✔ Network elemo-network      Created                                                                                                   0.0s 
 ✔ Volume "elemo_neo4j_data"  Created                                                                                                   0.0s 
 ✔ Volume "elemo_pg_data"     Created                                                                                                   0.0s 
 ✔ Container elemo-postgres   Started                                                                                                   1.1s 
 ✔ Container elemo-neo4j      Started                                                                                                   1.1s 
waiting 5 seconds to let the services boot
{"level":"info","ts":1713893471.1946611,"logger":"root","caller":"cli/root.go:147","msg":"config file loaded","path":"/Users/elmo/elemo/configs/development/config.local.gen.yml"}
{"level":"fatal","ts":1713893497.129895,"logger":"root","caller":"cli/auth_add_client.go:55","msg":"failed to initialize relational database","error":"failed to connect to `host=127.0.0.1 user=elemo database=elemo`: dial error (timeout: dial tcp 127.0.0.1:5432: connect: operation timed out)","stacktrace":"github.com/opcotech/elemo/cmd/elemo/cli.init.func1\n\t/Users/elmo/elemo/cmd/elemo/cli/auth_add_client.go:55\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/elmo/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/elmo/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/elmo/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/opcotech/elemo/cmd/elemo/cli.Execute\n\t/Users/elmo/elemo/cmd/elemo/cli/root.go:87\nmain.main\n\t/Users/elmo/elemo/cmd/elemo/main.go:18\nruntime.main\n\t/Users/elmo/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/runtime/proc.go:271"}
exit status 1

> git fetch origin && git status
On branch gabor/docker-compose-fix
Your branch is up to date with 'origin/gabor/docker-compose-fix'.

nothing to commit, working tree clean
```

### Bug report script fails hangs on Elmo version

The script outputs the following...

**OS information**

```text
Darwin makine-2.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64
```

**Local Go version**

```text
go version go1.22.2 darwin/arm64
```

Then, it hangs here.

After a couple of seconds, it shows the following.

**Elemo version**

```json
#13
```

Then it directly exits with a status code of 0.

**Comment by nizarmah** [comment]
I just ran into a new error thanks to the latest commit you just pushed 🥳 

```
./scripts/setup.sh: line 29: type: pnpm: not found
```

`pnpm` should be added to the list of development requirements

**Comment by nizarmah** [comment]
Once `brew install pnpm` later...

```
DONE! Now, you can start the backend and front-end services.
```

🥳

**Review by nizarmah — APPROVED** [review]
🙌🏼 awesome.

**Comment by gabor-boros** [comment]
@nizarmah 🎉 🥳 

Thanks for the continuous help with checking it! The issue is with `! type "pnpm" && npm install -g pnpm;`. The goal here was to install pnpm if not exists, however, it is obviously messed up.

**Comment by nizarmah** [comment]
Oh! Thanks for clarifying :D 

Also, I'm glad I could help!!

**Pull request merged**
